CREATE TABLE owner (ownername VARCHAR(20), ownerID INT PRIMARY KEY AUTO_INCREMENT);
CREATE TABLE species (speciesname VARCHAR(20), speciesID INT PRIMARY KEY AUTO_INCREMENT);
CREATE TABLE pet (petname VARCHAR(20), petID INT PRIMARY KEY AUTO_INCREMENT, speciesID INT(4), ownerID INT(4), sex CHAR(1), birth DATE, death DATE);


